//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conectorPDV001.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.254:8081/Service.asmx")]
        public string conectorPDV001_WebConectorServer_Service {
            get {
                return ((string)(this["conectorPDV001_WebConectorServer_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeAutorizacao")]
        public string conectorPDV001_webserviceAutorizacaoLoteHomo_NfeAutorizacao {
            get {
                return ((string)(this["conectorPDV001_webserviceAutorizacaoLoteHomo_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2")]
        public string conectorPDV001_webserviceInutilizacaoHomo_NfeRetAutorizacao {
            get {
                return ((string)(this["conectorPDV001_webserviceInutilizacaoHomo_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetAutorizacao")]
        public string conectorPDV001_webserviceRetAutorizacaoLoteHomo1_NfeRetAutorizacao {
            get {
                return ((string)(this["conectorPDV001_webserviceRetAutorizacaoLoteHomo1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string conectorPDV001_br_gov_rs_sefaz_nfe_homologacao_NfeAutorizacao {
            get {
                return ((string)(this["conectorPDV001_br_gov_rs_sefaz_nfe_homologacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetAutorizacao")]
        public string conectorPDV001_webserviceRetAutorizacaoLoteHomo_NfeRetAutorizacao {
            get {
                return ((string)(this["conectorPDV001_webserviceRetAutorizacaoLoteHomo_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfce.sefaz.am.gov.br/nfce-services-nac/services/NfeAutorizacao")]
        public string conectorPDV001_br_gov_am_sefaz_homnfce_NfeAutorizacao {
            get {
                return ((string)(this["conectorPDV001_br_gov_am_sefaz_homnfce_NfeAutorizacao"]));
            }
        }
    }
}
