//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace conector.consultacpf {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaCPFWebServiceTestDriveSoap", Namespace="ConsultaCPF")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization))]
    public partial class ConsultaCPFWebServiceTestDrive : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaSaldoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaHistoricoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaHistoricoPorTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSinteseCadastralSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSimplesSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDetalhadaSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaConcentreSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaChequeSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaTelefoneEnderecoSERASAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDetalhadaPlusSERASAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaCPFWebServiceTestDrive() {
            this.Url = global::conector.Properties.Settings.Default.conector_com_consultacpf_www_ConsultaCPFWebServiceTestDrive;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaSaldoClienteCompletedEventHandler ConsultaSaldoClienteCompleted;
        
        /// <remarks/>
        public event ConsultaHistoricoCompletedEventHandler ConsultaHistoricoCompleted;
        
        /// <remarks/>
        public event ConsultaHistoricoPorTokenCompletedEventHandler ConsultaHistoricoPorTokenCompleted;
        
        /// <remarks/>
        public event ConsultaSinteseCadastralSERASACompletedEventHandler ConsultaSinteseCadastralSERASACompleted;
        
        /// <remarks/>
        public event ConsultaSimplesSERASACompletedEventHandler ConsultaSimplesSERASACompleted;
        
        /// <remarks/>
        public event ConsultaDetalhadaSERASACompletedEventHandler ConsultaDetalhadaSERASACompleted;
        
        /// <remarks/>
        public event ConsultaConcentreSERASACompletedEventHandler ConsultaConcentreSERASACompleted;
        
        /// <remarks/>
        public event ConsultaChequeSERASACompletedEventHandler ConsultaChequeSERASACompleted;
        
        /// <remarks/>
        public event ConsultaTelefoneEnderecoSERASACompletedEventHandler ConsultaTelefoneEnderecoSERASACompleted;
        
        /// <remarks/>
        public event ConsultaDetalhadaPlusSERASACompletedEventHandler ConsultaDetalhadaPlusSERASACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaSaldoCliente", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente ConsultaSaldoCliente(string EMail, string Senha) {
            object[] results = this.Invoke("ConsultaSaldoCliente", new object[] {
                        EMail,
                        Senha});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSaldoClienteAsync(string EMail, string Senha) {
            this.ConsultaSaldoClienteAsync(EMail, Senha, null);
        }
        
        /// <remarks/>
        public void ConsultaSaldoClienteAsync(string EMail, string Senha, object userState) {
            if ((this.ConsultaSaldoClienteOperationCompleted == null)) {
                this.ConsultaSaldoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSaldoClienteOperationCompleted);
            }
            this.InvokeAsync("ConsultaSaldoCliente", new object[] {
                        EMail,
                        Senha}, this.ConsultaSaldoClienteOperationCompleted, userState);
        }
        
        private void OnConsultaSaldoClienteOperationCompleted(object arg) {
            if ((this.ConsultaSaldoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSaldoClienteCompleted(this, new ConsultaSaldoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaHistorico", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Historicos ConsultaHistorico(string EMail, string Senha, System.DateTime DataInicio, System.DateTime DataTermino) {
            object[] results = this.Invoke("ConsultaHistorico", new object[] {
                        EMail,
                        Senha,
                        DataInicio,
                        DataTermino});
            return ((Historicos)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaHistoricoAsync(string EMail, string Senha, System.DateTime DataInicio, System.DateTime DataTermino) {
            this.ConsultaHistoricoAsync(EMail, Senha, DataInicio, DataTermino, null);
        }
        
        /// <remarks/>
        public void ConsultaHistoricoAsync(string EMail, string Senha, System.DateTime DataInicio, System.DateTime DataTermino, object userState) {
            if ((this.ConsultaHistoricoOperationCompleted == null)) {
                this.ConsultaHistoricoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaHistoricoOperationCompleted);
            }
            this.InvokeAsync("ConsultaHistorico", new object[] {
                        EMail,
                        Senha,
                        DataInicio,
                        DataTermino}, this.ConsultaHistoricoOperationCompleted, userState);
        }
        
        private void OnConsultaHistoricoOperationCompleted(object arg) {
            if ((this.ConsultaHistoricoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaHistoricoCompleted(this, new ConsultaHistoricoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaHistoricoPorToken", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Historico ConsultaHistoricoPorToken(string EMail, string Senha, string Token) {
            object[] results = this.Invoke("ConsultaHistoricoPorToken", new object[] {
                        EMail,
                        Senha,
                        Token});
            return ((Historico)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaHistoricoPorTokenAsync(string EMail, string Senha, string Token) {
            this.ConsultaHistoricoPorTokenAsync(EMail, Senha, Token, null);
        }
        
        /// <remarks/>
        public void ConsultaHistoricoPorTokenAsync(string EMail, string Senha, string Token, object userState) {
            if ((this.ConsultaHistoricoPorTokenOperationCompleted == null)) {
                this.ConsultaHistoricoPorTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaHistoricoPorTokenOperationCompleted);
            }
            this.InvokeAsync("ConsultaHistoricoPorToken", new object[] {
                        EMail,
                        Senha,
                        Token}, this.ConsultaHistoricoPorTokenOperationCompleted, userState);
        }
        
        private void OnConsultaHistoricoPorTokenOperationCompleted(object arg) {
            if ((this.ConsultaHistoricoPorTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaHistoricoPorTokenCompleted(this, new ConsultaHistoricoPorTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaSinteseCadastralSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SinteseCadastral ConsultaSinteseCadastralSERASA(string EMail, string Senha, string Documento) {
            object[] results = this.Invoke("ConsultaSinteseCadastralSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento});
            return ((SinteseCadastral)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSinteseCadastralSERASAAsync(string EMail, string Senha, string Documento) {
            this.ConsultaSinteseCadastralSERASAAsync(EMail, Senha, Documento, null);
        }
        
        /// <remarks/>
        public void ConsultaSinteseCadastralSERASAAsync(string EMail, string Senha, string Documento, object userState) {
            if ((this.ConsultaSinteseCadastralSERASAOperationCompleted == null)) {
                this.ConsultaSinteseCadastralSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSinteseCadastralSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaSinteseCadastralSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento}, this.ConsultaSinteseCadastralSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaSinteseCadastralSERASAOperationCompleted(object arg) {
            if ((this.ConsultaSinteseCadastralSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSinteseCadastralSERASACompleted(this, new ConsultaSinteseCadastralSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaSimplesSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaSimples ConsultaSimplesSERASA(string EMail, string Senha, string Documento) {
            object[] results = this.Invoke("ConsultaSimplesSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento});
            return ((SERASAConsultaSimples)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSimplesSERASAAsync(string EMail, string Senha, string Documento) {
            this.ConsultaSimplesSERASAAsync(EMail, Senha, Documento, null);
        }
        
        /// <remarks/>
        public void ConsultaSimplesSERASAAsync(string EMail, string Senha, string Documento, object userState) {
            if ((this.ConsultaSimplesSERASAOperationCompleted == null)) {
                this.ConsultaSimplesSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSimplesSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaSimplesSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento}, this.ConsultaSimplesSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaSimplesSERASAOperationCompleted(object arg) {
            if ((this.ConsultaSimplesSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSimplesSERASACompleted(this, new ConsultaSimplesSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaDetalhadaSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaDetalhada ConsultaDetalhadaSERASA(string EMail, string Senha, string Documento) {
            object[] results = this.Invoke("ConsultaDetalhadaSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento});
            return ((SERASAConsultaDetalhada)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDetalhadaSERASAAsync(string EMail, string Senha, string Documento) {
            this.ConsultaDetalhadaSERASAAsync(EMail, Senha, Documento, null);
        }
        
        /// <remarks/>
        public void ConsultaDetalhadaSERASAAsync(string EMail, string Senha, string Documento, object userState) {
            if ((this.ConsultaDetalhadaSERASAOperationCompleted == null)) {
                this.ConsultaDetalhadaSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDetalhadaSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaDetalhadaSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento}, this.ConsultaDetalhadaSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaDetalhadaSERASAOperationCompleted(object arg) {
            if ((this.ConsultaDetalhadaSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDetalhadaSERASACompleted(this, new ConsultaDetalhadaSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaConcentreSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaConcentre ConsultaConcentreSERASA(string EMail, string Senha, string Documento) {
            object[] results = this.Invoke("ConsultaConcentreSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento});
            return ((SERASAConsultaConcentre)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaConcentreSERASAAsync(string EMail, string Senha, string Documento) {
            this.ConsultaConcentreSERASAAsync(EMail, Senha, Documento, null);
        }
        
        /// <remarks/>
        public void ConsultaConcentreSERASAAsync(string EMail, string Senha, string Documento, object userState) {
            if ((this.ConsultaConcentreSERASAOperationCompleted == null)) {
                this.ConsultaConcentreSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaConcentreSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaConcentreSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento}, this.ConsultaConcentreSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaConcentreSERASAOperationCompleted(object arg) {
            if ((this.ConsultaConcentreSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaConcentreSERASACompleted(this, new ConsultaConcentreSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaChequeSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaCheques ConsultaChequeSERASA(string EMail, string Senha, string Documento, string Banco, string Agencia, string ContaCorrente, string ChequeInicial, int ChequeInicialDigito) {
            object[] results = this.Invoke("ConsultaChequeSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento,
                        Banco,
                        Agencia,
                        ContaCorrente,
                        ChequeInicial,
                        ChequeInicialDigito});
            return ((SERASAConsultaCheques)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaChequeSERASAAsync(string EMail, string Senha, string Documento, string Banco, string Agencia, string ContaCorrente, string ChequeInicial, int ChequeInicialDigito) {
            this.ConsultaChequeSERASAAsync(EMail, Senha, Documento, Banco, Agencia, ContaCorrente, ChequeInicial, ChequeInicialDigito, null);
        }
        
        /// <remarks/>
        public void ConsultaChequeSERASAAsync(string EMail, string Senha, string Documento, string Banco, string Agencia, string ContaCorrente, string ChequeInicial, int ChequeInicialDigito, object userState) {
            if ((this.ConsultaChequeSERASAOperationCompleted == null)) {
                this.ConsultaChequeSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaChequeSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaChequeSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento,
                        Banco,
                        Agencia,
                        ContaCorrente,
                        ChequeInicial,
                        ChequeInicialDigito}, this.ConsultaChequeSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaChequeSERASAOperationCompleted(object arg) {
            if ((this.ConsultaChequeSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaChequeSERASACompleted(this, new ConsultaChequeSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaTelefoneEnderecoSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaTelefoneEndereco ConsultaTelefoneEnderecoSERASA(string EMail, string Senha, string Telefone) {
            object[] results = this.Invoke("ConsultaTelefoneEnderecoSERASA", new object[] {
                        EMail,
                        Senha,
                        Telefone});
            return ((SERASAConsultaTelefoneEndereco)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTelefoneEnderecoSERASAAsync(string EMail, string Senha, string Telefone) {
            this.ConsultaTelefoneEnderecoSERASAAsync(EMail, Senha, Telefone, null);
        }
        
        /// <remarks/>
        public void ConsultaTelefoneEnderecoSERASAAsync(string EMail, string Senha, string Telefone, object userState) {
            if ((this.ConsultaTelefoneEnderecoSERASAOperationCompleted == null)) {
                this.ConsultaTelefoneEnderecoSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTelefoneEnderecoSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaTelefoneEnderecoSERASA", new object[] {
                        EMail,
                        Senha,
                        Telefone}, this.ConsultaTelefoneEnderecoSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaTelefoneEnderecoSERASAOperationCompleted(object arg) {
            if ((this.ConsultaTelefoneEnderecoSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTelefoneEnderecoSERASACompleted(this, new ConsultaTelefoneEnderecoSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ConsultaCPF/ConsultaDetalhadaPlusSERASA", RequestNamespace="ConsultaCPF", ResponseNamespace="ConsultaCPF", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SERASAConsultaDetalhadaPlus ConsultaDetalhadaPlusSERASA(string EMail, string Senha, string Documento, string Estado) {
            object[] results = this.Invoke("ConsultaDetalhadaPlusSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento,
                        Estado});
            return ((SERASAConsultaDetalhadaPlus)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDetalhadaPlusSERASAAsync(string EMail, string Senha, string Documento, string Estado) {
            this.ConsultaDetalhadaPlusSERASAAsync(EMail, Senha, Documento, Estado, null);
        }
        
        /// <remarks/>
        public void ConsultaDetalhadaPlusSERASAAsync(string EMail, string Senha, string Documento, string Estado, object userState) {
            if ((this.ConsultaDetalhadaPlusSERASAOperationCompleted == null)) {
                this.ConsultaDetalhadaPlusSERASAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDetalhadaPlusSERASAOperationCompleted);
            }
            this.InvokeAsync("ConsultaDetalhadaPlusSERASA", new object[] {
                        EMail,
                        Senha,
                        Documento,
                        Estado}, this.ConsultaDetalhadaPlusSERASAOperationCompleted, userState);
        }
        
        private void OnConsultaDetalhadaPlusSERASAOperationCompleted(object arg) {
            if ((this.ConsultaDetalhadaPlusSERASACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDetalhadaPlusSERASACompleted(this, new ConsultaDetalhadaPlusSERASACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class Cliente {
        
        private string saldoField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaDetalhadaPlus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaTelefoneEndereco))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaCheques))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaConcentre))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaDetalhada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SERASAConsultaSimples))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinteseCadastral))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class Serialization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaDetalhadaPlus : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private int totalOcorrenciasField;
        
        private System.Data.DataSet pendenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Pendencias {
            get {
                return this.pendenciasField;
            }
            set {
                this.pendenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaTelefoneEndereco : Serialization {
        
        private string telefoneField;
        
        private string enderecoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string cEPField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaCheques : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private int totalOcorrenciasField;
        
        private string bancoField;
        
        private string agenciaField;
        
        private string contaCorrenteField;
        
        private string chequeInicialField;
        
        private string chequeInicialDigitoField;
        
        private System.Data.DataSet pendenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string ContaCorrente {
            get {
                return this.contaCorrenteField;
            }
            set {
                this.contaCorrenteField = value;
            }
        }
        
        /// <remarks/>
        public string ChequeInicial {
            get {
                return this.chequeInicialField;
            }
            set {
                this.chequeInicialField = value;
            }
        }
        
        /// <remarks/>
        public string ChequeInicialDigito {
            get {
                return this.chequeInicialDigitoField;
            }
            set {
                this.chequeInicialDigitoField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Pendencias {
            get {
                return this.pendenciasField;
            }
            set {
                this.pendenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaConcentre : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private int totalOcorrenciasField;
        
        private System.Data.DataSet pendenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Pendencias {
            get {
                return this.pendenciasField;
            }
            set {
                this.pendenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaDetalhada : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private int totalOcorrenciasField;
        
        private System.Data.DataSet pendenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Pendencias {
            get {
                return this.pendenciasField;
            }
            set {
                this.pendenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SERASAConsultaSimples : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private int totalOcorrenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class SinteseCadastral : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascField;
        
        private string situacaoDocumentoField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class Historico {
        
        private string documentoField;
        
        private string tokenField;
        
        private string viaField;
        
        private string consultaField;
        
        private string dataHoraField;
        
        private string valorDebitadoField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        public string Consulta {
            get {
                return this.consultaField;
            }
            set {
                this.consultaField = value;
            }
        }
        
        /// <remarks/>
        public string DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
        
        /// <remarks/>
        public string ValorDebitado {
            get {
                return this.valorDebitadoField;
            }
            set {
                this.valorDebitadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ConsultaCPF")]
    public partial class Historicos {
        
        private string mensagemField;
        
        private int totalConsultasField;
        
        private System.Data.DataSet historicoField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public int TotalConsultas {
            get {
                return this.totalConsultasField;
            }
            set {
                this.totalConsultasField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Historico {
            get {
                return this.historicoField;
            }
            set {
                this.historicoField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaSaldoClienteCompletedEventHandler(object sender, ConsultaSaldoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSaldoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSaldoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaHistoricoCompletedEventHandler(object sender, ConsultaHistoricoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaHistoricoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaHistoricoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Historicos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Historicos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaHistoricoPorTokenCompletedEventHandler(object sender, ConsultaHistoricoPorTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaHistoricoPorTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaHistoricoPorTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Historico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Historico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaSinteseCadastralSERASACompletedEventHandler(object sender, ConsultaSinteseCadastralSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSinteseCadastralSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSinteseCadastralSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SinteseCadastral Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SinteseCadastral)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaSimplesSERASACompletedEventHandler(object sender, ConsultaSimplesSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSimplesSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSimplesSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaSimples Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaSimples)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaDetalhadaSERASACompletedEventHandler(object sender, ConsultaDetalhadaSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDetalhadaSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDetalhadaSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaDetalhada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaDetalhada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaConcentreSERASACompletedEventHandler(object sender, ConsultaConcentreSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaConcentreSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaConcentreSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaConcentre Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaConcentre)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaChequeSERASACompletedEventHandler(object sender, ConsultaChequeSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaChequeSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaChequeSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaCheques Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaCheques)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaTelefoneEnderecoSERASACompletedEventHandler(object sender, ConsultaTelefoneEnderecoSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTelefoneEnderecoSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTelefoneEnderecoSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaTelefoneEndereco Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaTelefoneEndereco)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaDetalhadaPlusSERASACompletedEventHandler(object sender, ConsultaDetalhadaPlusSERASACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDetalhadaPlusSERASACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDetalhadaPlusSERASACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SERASAConsultaDetalhadaPlus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SERASAConsultaDetalhadaPlus)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591